### ISSUE TITLE
正确输入账号密码登录失败

### ISSUE THREAD

**Issue by Az0s** [Hyiker/bupt-gym-reserve#15]
<img width="358" alt="Screen Shot 2021-09-14 at 11 02 21 AM" src="https://user-images.githubusercontent.com/42002876/133187859-9a43ba31-5956-4949-842d-d15e466eef9f.png">
表单中'lt'项与session创建时网页中'lt‘值相同，是不是因此导致无法正常登陆？
<img width="554" alt="image" src="https://user-images.githubusercontent.com/42002876/133188010-a54dd619-b558-473c-8540-400a144b4dee.png">

**Comment by Az0s** [comment]
截图不是同一个session截的 lt值不一样 忽略忽略

**Comment by Hyiker** [comment]
登录失败是因为登录接口从原来的网页改成了统一认证，我暂时没有时间维护这个项目，欢迎有能力的人来pr修复
